py_library(
    name = "auth_service",
    srcs = ["auth_service.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/infrastructures/db:database",
        "//src/infrastructures/db:redis_db",
        "//src/common:settings",
    ]
)

py_test(
    name = "test_auth_service",
    srcs = ["tests/test_auth_service.py"],
    main = "tests/test_auth_service.py",
    timeout = "short",
    args = [
        "-vv",
    ],
    tags = [
        "local",
        "requires-network",
        "yourit",
    ],
    deps = [
        "//src/services/auth:auth_service",
        "//src/services/business:user_service",
        "//src/exceptions:exceptions",
        "//src/common:crypto",
        "//src/common:settings",
        "//src/infrastructures/db:redis_db",
    ],
)
