py_library(
    name = "user_schema",
    srcs = ["user_schema.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "health_schema",
    srcs = ["health_schema.py"],
    visibility = ["//visibility:public"],
)
