# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci-workflow

on:
  push

permissions:
  contents: read

concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Setup Bazel
      id: setup-bazel
      uses: bazelbuild/setup-bazelisk@v3

    - name: Get changed files
      id: changed-files
      continue-on-error: true
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'

    - name: Install CI requirements
      id: install-ci-requirements
      run: |
        make install

    - name: Check incremental changes
      id: check-incremental-changes
      run: |
        make verify_changes CHANGES=${{ steps.changed-files.outputs.all }}
    
    - name: Install flyway
      id: install-flyway
      run: |
        FLYWAY_VERSION=10.3.0
        OS=linux-x64
        curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}-${OS}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz \
          && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 \
          && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz \
          && ln -s $(realpath flyway) /usr/local/bin/flyway
    
    - name: Start docker-compose
      id: start-docker-compose
      run: |
        make docker_compose_up

    - name: Run integration tests
      id: integration-tests
      run: |
        make migrate
        make run_integration_tests
